spring.application.name=OrderService
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
management.endpoints.web.exposure.include=health,info
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
# Redis configuration
spring.redis.host=localhost
spring.redis.port=6379
redis.ttl=86400

# GraphQL Configuration
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

